### ISSUE TITLE
[Feature] Add support for clipboard history

### ISSUE THREAD

**Issue by ghost** [Linus789/wl-clip-persist#1]
It might be useful for people that want to use wl-clip-persist along with rofi/wofi. 

## Example usage
```
wl-clip-persist --list | rofi -dmenu -m -1 | wl-copy
```

**Comment by Linus789** [comment]
It is possible to use this application alongside [cliphist](https://github.com/sentriz/cliphist). Does that help?

**Comment by Linus789** [comment]
Yes, this should work as long as you listen for keyboard changes with
```
wl-paste --watch cliphist store
```

**Comment by Linus789** [comment]
> It indeed works, but would it be able to copy images too?

wl-clip-persist should be able to copy images too, even if cliphist runs in the background. But you can also disable that feature.

> Also, sorry if this is not planned, but couldn't it be possible to make an option to list the copied stuff? I think it would be much easier since Cliphist lists stuff via numbers and it also copies those. But I guess that can be easily fixable via sed.

I have no plans to add a clipboard history, if that’s what you mean. The numbers cliphist lists are for decoding (`cliphist decode`). There shouldn’t be any numbers after the decoding, so it’s kinda odd that these numbers are copied for you.
