### ISSUE TITLE
Screenshot lacks bottom part when wl-clip-persist launched.

### ISSUE THREAD

**Issue by Memoframe** [Linus789/wl-clip-persist#10]
Linux arch 6.8.7-arch1-1.
Hyprland.
Hyprshot or grim for screenshots, same issue for both.
On system start I run _wl-clip-persist --clipboard regular_

wl-clip-persist cuts out bottom of the screenshot.
Sometimes it's around half, sometimes it's almost all image.
If screenshot is taken and wl-clip-persist is not running it's ok.
Once wl-clip-persist kicks in, this screenshot cuts out.
As a workaround I ~kill _wl-clip-persist for several seconds _bind = , Print, exec, pkill wl-clip-persist && hyprshot -m region -d --clipboard-only && sleep 6 && wl-clip-persist --clipboard regular_~ <- that is bad so I restricted data size for which it will work, so now I run _wl-clip-persist --clipboard regular -l 4096_ on system start, it's enough for any text I may copy but less than any image I'll copy.

Without wl-clip-persist:
![image](https://github.com/Linus789/wl-clip-persist/assets/15750345/de7605bf-e9de-45a5-8d26-62f980ffd76d)

With wl-clip-persist:
![image](https://github.com/Linus789/wl-clip-persist/assets/15750345/04f490e2-7283-405b-b487-1e34fde700f6)

Any ideas where to dig, maybe I need to provide some additional info?
Or maybe it's not wl-clip-persist issue?

**Comment by The-Lost-Light** [comment]
I have the same problem i test by discord
When I copy the image from swappy it alwayse have half of image
![20240427-203237](https://github.com/Linus789/wl-clip-persist/assets/8400760/8b2bcff6-281f-47b3-8a0f-b8796a07b9cb)
However  it copy fine from the eog
![20240427-203606](https://github.com/Linus789/wl-clip-persist/assets/8400760/b7a674e3-d494-4f60-b988-bf7eab0a52ff)

**Comment by Memoframe** [comment]
Quick addition, same behavior for pictures copied, for example from browser, by right click -> copy image

**Comment by Linus789** [comment]
Thanks for finding this bug and I'm sorry for the inconvenience it caused! Could you test if this branch fixes the problem? https://github.com/Linus789/wl-clip-persist/tree/fix-blocking-writes

**Comment by Memoframe** [comment]
> Thanks for finding this bug and I'm sorry for the inconvenience it caused! Could you test if this branch fixes the problem? https://github.com/Linus789/wl-clip-persist/tree/fix-blocking-writes

I think it works but since I have no idea what I'm doing can you confirm my actions were correct?

Removed aur wl-clip-persist
Cloned repository
Listed branches
Checkout remotes/origin/fix-blocking-writes
Build 
Copy only file wl-clip-persist from release to /usr/bin

Follow up questions:
I assume after you update main, I should delete this one and install aur (when it will be updated too) again to have automated updates when I run yay?

**Comment by Linus789** [comment]
> can you confirm my actions were correct?

Yes, that should work! To be precise, you also have to restart wl-clip-persist so it uses the new binary, but I assume that's what you did.

> I assume after you update main, I should delete this one and install aur (when it will be updated too) again to have automated updates when I run yay?

Yes :)

> I think it works

Thanks for the info, I'll probably create a new release within the next day

**Comment by Memoframe** [comment]
>  To be precise, you also have to restart wl-clip-persist so it uses the new binary, but I assume that's what you did.
I killed it before deleting aur and launched after new one was copied to /usr/bin.
I also checked if it's running after launching it and checked if text copied from text editor persists after closing text editor.

**Comment by Linus789** [comment]
Thanks, good work! :)

In case you are interested: It's not like you have to uninstall the AUR package. You could keep the AUR package installed, but kill the running process as you did. Then after building you could run wl-clip-persist directly from the build directory and this should have the same effect. ^^
```
$ ./target/release/wl-clip-persist -c regular
```

**Comment by Memoframe** [comment]
Now I know a bit more, reporting an issue was not a bad idea after all :D

**Comment by Linus789** [comment]
> Now I know a bit more, reporting an issue was not a bad idea after all :D

Nice to hear :)

New version with fix: https://github.com/Linus789/wl-clip-persist/releases/tag/v0.4.1
