### ISSUE TITLE
Add clipboard auto delete timer 

### ISSUE THREAD

**Issue by MrDisguised** [Linus789/wl-clip-persist#2]
It will be awesome if the clipboard can delete history after a given interval.

**Comment by Linus789** [comment]
That should be possible (I think) but would require an async rewrite, which isn’t as easy and straightforward as it might sound. I don’t have the time for that right now, but I’ll leave this issue open.

**Comment by MrDisguised** [comment]
ic :(

**Comment by Linus789** [comment]
I am sorry to inform you that I deem this feature to be out of scope. After thinking about this more, it does not make sense to restrict that option to wl-clip-persist, as other persons who dont wan't to use this application might want to clear their clipboard after a specified amount of time, too. Therefore, I think it should be its own program, and I'm confident that it would work alongside this application.

It seems like there are already some scripts for what you want: https://knrdl.github.io/posts/wayland-clipboard-clean/
It might have its disadvantages, but it might be good enough.
